CPPFLAGS = -ansi -Wall -g

Proj5.out: Proj5.o Proj5Aux.h GridGame.h TicTacToe.h Reversi.h Life.h Proj5Aux.cpp GridGame.cpp TicTacToe.cpp Reversi.cpp Life.cpp
	g++ Proj5.cpp Proj5Aux.cpp GridGame.cpp TicTacToe.cpp Reversi.cpp Life.cpp -lg -o Proj5.out

clean:
	rm -f Proj5.o Proj5Aux.o GridGame.o TicTacToe.o Reversi.o Life.o Proj5.out

